image:
- Ubuntu
- Visual Studio 2015

platform:
  - x86
  - x64
  
configuration:
- Debug
- Release

for:
  - 
    matrix:
      only:
        - configuration: Debug
    environment:
      config: Debug

  - 
    matrix:
      only:
        - configuration: Release
    environment:
      config: Release

before_build:
  - cmake -H. -B_builds -DCMAKE_BUILD_TYPE=%config%
  - cmake --build . --target generator
  - cmake --build . --target database

build_script:
  - cmake --build _builds --config %config%

test_script:
  - ps: cd _builds
  - ctest -VV -C %config%