image:
- Ubuntu
- Visual Studio 2015

platform:
  - x86
  - x64
  
configuration:
- Debug
- Release

for:
  - 
    matrix:
      only:
        - configuration: Debug
    environment:
      config: Debug

  - 
    matrix:
      only:
        - configuration: Release
    environment:
      config: Release

  -
    matrix:
      only:
        - image: Ubuntu
    install:
    - apt-get install monodevelop
    before_build:
    - mdtool build generator/brutezone.csproj

build_script:
  - cmake -H. -B_builds -DCMAKE_BUILD_TYPE=%config%
  - cmake --build _builds --config %config%

test_script:
  - ps: cd _builds
  - ctest -VV -C %config%